export default [
  { name: "venusaur", id: 3 },
  { name: "charizard", id: 6 },
  { name: "blastoise", id: 9 },
  { name: "butterfree", id: 12 },
  { name: "beedrill", id: 15 },
  { name: "pidgeot", id: 18 },
  { name: "raticate", id: 20 },
  { name: "fearow", id: 22 },
  { name: "arbok", id: 24 },
  { name: "raichu", id: 26 },
  { name: "sandslash", id: 28 },
  { name: "nidoqueen", id: 31 },
  { name: "nidoking", id: 34 },
  { name: "clefable", id: 36 },
  { name: "ninetales", id: 38 },
  { name: "wigglytuff", id: 40 },
  { name: "golbat", id: 42 },
  { name: "vileplume", id: 45 },
  { name: "parasect", id: 47 },
  { name: "venomoth", id: 49 },
  { name: "dugtrio", id: 51 },
  { name: "persian", id: 53 },
  { name: "golduck", id: 55 },
  { name: "primeape", id: 57 },
  { name: "arcanine", id: 59 },
];
